import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';

import { MermaidGeneratedSharedModule, FunnelGeneratedModule } from '../generated/module.js';
import { FunnelTokenBuilder } from './tokenBuilder.js';
import { FunnelValueConverter } from './valueConverter.js';

/**
 * Declaration of `Funnel` services.
 */
interface FunnelAddedServices {
  parser: {
    TokenBuilder: FunnelTokenBuilder;
    ValueConverter: FunnelValueConverter;
  };
}

/**
 * Union of Langium default services and `Funnel` services.
 */
export type FunnelServices = LangiumCoreServices & FunnelAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `Funnel` services.
 */
export const FunnelModule: Module<
  FunnelServices,
  PartialLangiumCoreServices & FunnelAddedServices
> = {
  parser: {
    TokenBuilder: () => new FunnelTokenBuilder(),
    ValueConverter: () => new FunnelValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createFunnelServices(context: DefaultSharedCoreModuleContext = EmptyFileSystem): {
  shared: LangiumSharedCoreServices;
  Funnel: FunnelServices;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const Funnel: FunnelServices = inject(
    createDefaultCoreModule({ shared }),
    FunnelGeneratedModule,
    FunnelModule
  );
  shared.ServiceRegistry.register(Funnel);
  return { shared, Funnel };
}
