import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';

import { MermaidGeneratedSharedModule, FunnelFlowGeneratedModule } from '../generated/module.js';
import { FunnelFlowTokenBuilder } from './tokenBuilder.js';
import { FunnelFlowValueConverter } from './valueConverter.js';

/**
 * Declaration of `FunnelFlow` services.
 */
interface FunnelFlowAddedServices {
  parser: {
    TokenBuilder: FunnelFlowTokenBuilder;
    ValueConverter: FunnelFlowValueConverter;
  };
}

/**
 * Union of Langium default services and `FunnelFlow` services.
 */
export type FunnelFlowServices = LangiumCoreServices & FunnelFlowAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `FunnelFlow` services.
 */
export const FunnelFlowModule: Module<
  FunnelFlowServices,
  PartialLangiumCoreServices & FunnelFlowAddedServices
> = {
  parser: {
    TokenBuilder: () => new FunnelFlowTokenBuilder(),
    ValueConverter: () => new FunnelFlowValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createFunnelFlowServices(
  context: DefaultSharedCoreModuleContext = EmptyFileSystem
): {
  shared: LangiumSharedCoreServices;
  FunnelFlow: FunnelFlowServices;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const FunnelFlow: FunnelFlowServices = inject(
    createDefaultCoreModule({ shared }),
    FunnelFlowGeneratedModule,
    FunnelFlowModule
  );
  shared.ServiceRegistry.register(FunnelFlow);
  return { shared, FunnelFlow };
}
