// cspell:ignore smartshape
import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';

import { MermaidGeneratedSharedModule, SmartShapeGeneratedModule } from '../generated/module.js';
import { SmartShapeTokenBuilder } from './tokenBuilder.js';
import { SmartShapeValueConverter } from './valueConverter.js';

/**
 * Declaration of `SmartShape` services.
 */
interface SmartShapeAddedServices {
  parser: {
    TokenBuilder: SmartShapeTokenBuilder;
    ValueConverter: SmartShapeValueConverter;
  };
}

/**
 * Union of Langium default services and `SmartShape` services.
 */
export type SmartShapeServices = LangiumCoreServices & SmartShapeAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `SmartShape` services.
 */
export const SmartShapeModule: Module<
  SmartShapeServices,
  PartialLangiumCoreServices & SmartShapeAddedServices
> = {
  parser: {
    TokenBuilder: () => new SmartShapeTokenBuilder(),
    ValueConverter: () => new SmartShapeValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSmartShapeServices(
  context: DefaultSharedCoreModuleContext = EmptyFileSystem
): {
  shared: LangiumSharedCoreServices;
  SmartShape: SmartShapeServices;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const SmartShape: SmartShapeServices = inject(
    createDefaultCoreModule({ shared }),
    SmartShapeGeneratedModule,
    SmartShapeModule
  );
  shared.ServiceRegistry.register(SmartShape);
  return { shared, SmartShape };
}
